services:
  aidIQ-db:
    image: postgres:latest
    container_name: aidIQ-db
    restart: always
    environment:
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    volumes:
      - aidIQ-db_data:/var/lib/postgresql/data
    ports:
      - '${DB_PORT}:5432'

volumes:
  aidIQ-db_data:
